import React,{useEffect,useMemo,useRef,useState} from "react";
import {createRoot} from "react-dom/client";
import {BrowserMultiFormatReader} from "@zxing/browser";
import "./style.css";

const API="/api"; const key="yps_token";
const token=()=>localStorage.getItem(key)||"";
async function api(path:string,opt:any={}){const r=await fetch(API+path,{...opt,headers:{...(opt.body instanceof FormData?{}:{"Content-Type":"application/json"}),...(token()?{Authorization:`Bearer ${token()}`}:{}) ,...(opt.headers||{})}});let d:any;try{d=await r.json()}catch{d={}};if(!r.ok)throw Error(d.detail||d.message||"Request failed");return d}
const money=(n:number)=>`₹${Number(n||0).toFixed(2)}`;
const DB="YPS_OFFLINE_V2";
function idb():Promise<IDBDatabase>{return new Promise((ok,no)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains("catalog"))d.createObjectStore("catalog",{keyPath:"id"});if(!d.objectStoreNames.contains("sales"))d.createObjectStore("sales",{keyPath:"idempotency_key"});};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function put(store:string,v:any){const d=await idb();return new Promise<void>((ok,no)=>{const r=d.transaction(store,"readwrite").objectStore(store).put(v);r.onsuccess=()=>ok();r.onerror=()=>no(r.error)})}
async function all(store:string){const d=await idb();return new Promise<any[]>((ok,no)=>{const r=d.transaction(store).objectStore(store).getAll();r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function del(store:string,id:any){const d=await idb();return new Promise<void>((ok,no)=>{const r=d.transaction(store,"readwrite").objectStore(store).delete(id);r.onsuccess=()=>ok();r.onerror=()=>no(r.error)})}

function App(){
 const [view,setView]=useState("shop"),[products,setProducts]=useState<any[]>([]),[cats,setCats]=useState<any[]>([]),[cart,setCart]=useState<any[]>([]),[q,setQ]=useState(""),[dash,setDash]=useState<any>({}),[orders,setOrders]=useState<any[]>([]),[customers,setCustomers]=useState<any[]>([]),[suppliers,setSuppliers]=useState<any[]>([]),[ai,setAi]=useState<any>(),[cmd,setCmd]=useState(""),[login,setLogin]=useState(!token()),[user,setUser]=useState<any>(),[camera,setCamera]=useState(false),[voice,setVoice]=useState(false),[sync,setSync]=useState("online"),[upi,setUpi]=useState<any>(),[audit,setAudit]=useState<any[]>([]),[notice,setNotice]=useState("");
 const load=async()=>{try{const [p,c,d,o,cu,su]=await Promise.all([api(`/products?q=${encodeURIComponent(q)}`),api("/categories"),api("/dashboard"),api("/orders"),api("/customers"),api("/suppliers")]);setProducts(p);setCats(c);setDash(d);setOrders(o);setCustomers(cu);setSuppliers(su);for(const x of p)await put("catalog",x);setSync(navigator.onLine?"online":"offline")}catch{setSync("offline");try{setProducts(await all("catalog"))}catch{}}};
 useEffect(()=>{load();const on=()=>{setSync("online");flush()};const off=()=>setSync("offline");window.addEventListener("online",on);window.addEventListener("offline",off);return()=>{window.removeEventListener("online",on);window.removeEventListener("offline",off)}},[]);
 const total=useMemo(()=>cart.reduce((a,x)=>a+x.price*x.qty,0),[cart]);
 const add=(p:any)=>setCart(c=>{const x=c.find(i=>i.id===p.id);return x?c.map(i=>i.id===p.id?{...i,qty:i.qty+1}:i):[...c,{id:p.id,name:p.name,price:p.discount_price??p.selling_price,qty:1}]});
 const change=(id:number,d:number)=>setCart(c=>c.map(x=>x.id===id?{...x,qty:Math.max(0,x.qty+d)}:x).filter(x=>x.qty));
 const sale=async(method="cash")=>{if(!cart.length)return;const payload={items:cart.map(x=>({product_id:x.id,quantity:x.qty,unit_price:x.price})),payment_method:method,idempotency_key:crypto.randomUUID()};if(!navigator.onLine){await put("sales",{...payload,status:"PENDING_SYNC",timestamp:Date.now()});setNotice("Offline sale saved. It will sync automatically.");setCart([]);return}try{await api("/sales",{method:"POST",body:JSON.stringify(payload)});setCart([]);setNotice("Sale completed");load()}catch(e:any){setNotice(e.message)}};
 async function flush(){const rows=await all("sales");for(const x of rows){try{await api("/sales/sync",{method:"POST",body:JSON.stringify(x)});await del("sales",x.idempotency_key)}catch{}}}
 const aiRun=async(confirm=false)=>{try{const d=await api("/ai/command",{method:"POST",body:JSON.stringify({text:cmd,confirm})});setAi(d)}catch(e:any){setAi({error:e.message})}};
 const scanCode=async(code:string)=>{setCamera(false);try{const p=await api(`/barcode/${encodeURIComponent(code)}`);add(p);setNotice(`${p.name} added`)}catch{setNotice("Unknown barcode — create the product or enter it manually.")}};
 async function makeUPI(){try{setUpi(await api(`/upi/qr?amount=${total}&reference=POS-${Date.now()}`))}catch(e:any){setNotice(e.message)}}
 async function loadAudit(){try{setAudit(await api("/audit"))}catch(e:any){setNotice(e.message)}}
 if(login)return <Login onLogin={u=>{setUser(u);setLogin(false);load()}}/>;
 return <div className="app"><header><b>YASH PROVISION STORE</b><span>{user?.role} • <i>{sync}</i></span></header><nav>{["shop","dashboard","products","inventory","orders","customers","suppliers","purchases","reports","ai","barcode","audit","settings"].map(v=><button className={view===v?"active":""} onClick={()=>{setView(v);if(v==="audit")loadAudit()}}>{v}</button>)}<button onClick={()=>{localStorage.removeItem(key);location.reload()}}>Logout</button></nav><main>
 {view==="shop"&&<><section className="hero"><div><small>OFFLINE-FIRST RETAIL POS</small><h1>Fast billing, real stock.</h1><p>Server-authoritative inventory with UUID idempotency.</p></div><b>{dash.low_stock||0}<small> low stock</small></b></section><div className="toolbar"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()} placeholder="Search product / Hindi / SKU / barcode"/><button onClick={()=>setCamera(true)}>📷 Scan</button><button onClick={()=>setVoice(true)}>🎙 Voice</button></div><div className="grid">{products.map(p=><article className="card"><div className="pic">{p.image_url?<img src={p.image_url}/>:"🛍️"}</div><h3>{p.name}</h3><small>{p.brand} • {p.unit} • {p.barcode}</small><strong>{money(p.discount_price??p.selling_price)}</strong><span>Stock: {p.stock}</span><button disabled={p.stock<=0} onClick={()=>add(p)}>Add</button></article>)}</div><aside className="cart"><h3>Cart</h3>{cart.map(x=><div className="line"><span>{x.name}<small>{money(x.price)} × {x.qty}</small></span><span><button onClick={()=>change(x.id,-1)}>−</button><button onClick={()=>change(x.id,1)}>+</button></span></div>)}<h2>{money(total)}</h2><div className="actions"><button className="primary" onClick={()=>sale("cash")}>Cash</button><button onClick={makeUPI}>UPI QR</button><button onClick={()=>sale("credit")}>Udhaar</button></div></aside></>}
 {view==="dashboard"&&<Dashboard dash={dash}/>} {view==="products"&&<Products products={products} cats={cats} reload={load}/>} {view==="inventory"&&<Inventory products={products} reload={load}/>} {view==="orders"&&<Orders orders={orders} reload={load}/>} {view==="customers"&&<Customers customers={customers} reload={load}/>} {view==="suppliers"&&<Suppliers suppliers={suppliers}/>} {view==="purchases"&&<Purchases products={products} suppliers={suppliers} reload={load}/>} {view==="reports"&&<Reports/>} {view==="ai"&&<AI cmd={cmd} setCmd={setCmd} ai={ai} run={aiRun}/>} {view==="barcode"&&<Barcode products={products}/>} {view==="audit"&&<Audit rows={audit}/>} {view==="settings"&&<Settings/>}
 </main>{notice&&<div className="toast" onClick={()=>setNotice("")}>{notice}</div>}{camera&&<Camera close={()=>setCamera(false)} onCode={scanCode}/>} {voice&&<Voice close={()=>setVoice(false)} setCmd={setCmd} onAI={()=>{setVoice(false);setView("ai");aiRun(false)}}/>} {upi&&<Modal title="UPI Payment QR" close={()=>setUpi(undefined)}><p>Payment is NOT confirmed by QR generation. Confirm settlement before completing a paid transaction.</p><img className="qr" src={`data:image/png;base64,${upi.png_base64}`}/><code>{upi.uri}</code><button className="primary" onClick={()=>{setUpi(undefined);sale("upi")}}>I VERIFIED PAYMENT — COMPLETE SALE</button></Modal>}</div>
}
function Dashboard({dash}:any){return <><h2>Owner Dashboard</h2><div className="metrics">{[["Today Sales",money(dash.today_sales)],["Orders",dash.today_orders],["Stock Value",money(dash.stock_value)],["Low Stock",dash.low_stock],["Out of Stock",dash.out_of_stock],["Udhaar",money(dash.udhaar)],["Expenses",money(dash.expenses)],["Expiry ≤30d",dash.expiry_30]].map(x=><div className="metric"><b>{x[1]}</b><span>{x[0]}</span></div>)}</div><section className="panel"><h3>Low stock</h3>{(dash.low_products||[]).map((p:any)=><div className="row">{p.name}<b>{p.stock} {p.unit}</b></div>)}</section></>}
function Products({products,reload}:any){const [f,setF]=useState<any>({name:"",selling_price:0,purchase_price:0,stock:0,unit:"piece"});const save=async()=>{try{await api("/products",{method:"POST",body:JSON.stringify(f)});setF({name:"",selling_price:0,purchase_price:0,stock:0,unit:"piece"});reload()}catch(e:any){alert(e.message)}};return <><h2>Products</h2><section className="panel form"><input placeholder="Name" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><input placeholder="Hindi name" value={f.hindi_name||""} onChange={e=>setF({...f,hindi_name:e.target.value})}/><input placeholder="SKU" value={f.sku||""} onChange={e=>setF({...f,sku:e.target.value})}/><input placeholder="Barcode" value={f.barcode||""} onChange={e=>setF({...f,barcode:e.target.value})}/><input type="number" placeholder="Selling price" value={f.selling_price} onChange={e=>setF({...f,selling_price:+e.target.value})}/><input type="number" placeholder="Opening stock" value={f.stock} onChange={e=>setF({...f,stock:+e.target.value})}/><button onClick={save}>Create Product</button></section><div className="table"><table><thead><tr><th>Name</th><th>SKU</th><th>Barcode</th><th>Price</th><th>Stock</th><th>Status</th></tr></thead><tbody>{products.map((p:any)=><tr><td>{p.name}</td><td>{p.sku}</td><td>{p.barcode}</td><td>{money(p.selling_price)}</td><td>{p.stock}</td><td>{p.active?"Active":"Archived"}</td></tr>)}</tbody></table></div></>}
function Inventory({products,reload}:any){return <><h2>Inventory / FEFO</h2>{products.map((p:any)=><div className="panel row"><span><b>{p.name}</b><small>{p.stock} {p.unit} • reorder {p.reorder_level}</small></span><button onClick={async()=>{const q=Number(prompt("Adjustment quantity (+/-)")||0);if(q)try{await api(`/products/${p.id}/stock`,{method:"POST",body:JSON.stringify({quantity:q,reason:"manual adjustment"})});reload()}catch(e:any){alert(e.message)}}}>Adjust</button></div>)}</>}
function Orders({orders,reload}:any){return <><h2>Online Orders</h2>{orders.map((o:any)=><div className="panel row"><span><b>{o.order_no}</b><small>{o.customer_name} • {o.mobile}</small></span><select value={o.status} onChange={async e=>{try{await api(`/orders/${o.id}`,{method:"PATCH",body:JSON.stringify({status:e.target.value})});reload()}catch(err:any){alert(err.message)}}}>{["Placed","Accepted","Preparing","Ready","Out for Delivery","Completed","Cancelled","Rejected"].map(s=><option>{s}</option>)}</select></div>)}</>}
function Customers({customers,reload}:any){return <><h2>Customers / Udhaar</h2>{customers.map((c:any)=><div className="panel row"><span><b>{c.name}</b><small>{c.mobile}</small></span><span>Due {money(c.credit_balance)} <button onClick={async()=>{const a=Number(prompt("Payment amount")||0);if(a)try{await api(`/customers/${c.id}/payment`,{method:"POST",body:JSON.stringify({amount:a})});reload()}catch(e:any){alert(e.message)}}}>Payment</button></span></div>)}</>}
function Suppliers({suppliers}:any){return <><h2>Supplier Payables</h2>{suppliers.map((s:any)=><div className="panel row"><span><b>{s.name}</b><small>{s.phone}</small></span><b>{money(s.due)} due</b></div>)}</>}
function Purchases({products,reload}:any){const [pid,setPid]=useState(products[0]?.id||0);return <><h2>Purchase / Batch / Expiry</h2><section className="panel form"><select value={pid} onChange={e=>setPid(+e.target.value)}>{products.map(p=><option value={p.id}>{p.name}</option>)}</select><input id="pq" placeholder="Quantity"/><input id="pr" placeholder="Purchase rate"/><input id="bn" placeholder="Batch number"/><input id="mf" placeholder="MFG YYYY-MM-DD"/><input id="ex" placeholder="Expiry YYYY-MM-DD"/><button onClick={async()=>{const v=(id:string)=>(document.getElementById(id) as HTMLInputElement).value;try{await api("/purchases",{method:"POST",body:JSON.stringify({items:[{product_id:pid,quantity:+v("pq"),rate:+v("pr"),batch_no:v("bn"),mfg_date:v("mf")||undefined,expiry_date:v("ex")||undefined}],paid:0,idempotency_key:crypto.randomUUID()})});reload()}catch(e:any){alert(e.message)}}}>Receive Purchase</button></section></>}
function Reports(){const [d,setD]=useState<any>();useEffect(()=>{api("/reports/summary").then(setD)},[]);return <><h2>Reports</h2>{d&&<div className="metrics">{Object.entries(d).map(([k,v])=><div className="metric"><b>{typeof v==="number"?money(v as number):String(v)}</b><span>{k}</span></div>)}</div>}<div className="toolbar"><a href={`${API}/reports/products.csv`}>Products CSV</a><a href={`${API}/reports/sales.csv`}>Sales CSV</a><a href={`${API}/reports/summary.xlsx`}>Summary XLSX</a><a href={`${API}/reports/summary.pdf`}>Summary PDF</a></div></>}
function AI({cmd,setCmd,ai,run}:any){return <><h2>AI Assistant</h2><section className="panel"><textarea value={cmd} onChange={e=>setCmd(e.target.value)} placeholder="Parle-G 5 rupaye wale 36 packet stock mein add karo"/><button onClick={()=>run(false)}>Preview</button>{ai?.kind==="preview"&&<div className="confirm"><b>Action:</b> {ai.action}<br/><b>Product:</b> {ai.product}<br/><b>Old:</b> {ai.old_value}<br/><b>New:</b> {ai.new_value}<br/><button className="primary" onClick={()=>run(true)}>CONFIRM</button><button onClick={()=>{}}>EDIT</button><button onClick={()=>setCmd("")}>CANCEL</button></div>}<pre>{JSON.stringify(ai,null,2)}</pre><small>Provider-backed when configured; no AI action receives SQL access. Mutations require confirmation.</small></section></>}
function Barcode({products}:any){const [ids,setIds]=useState<number[]>([]),[qty,setQty]=useState(30);return <><h2>Barcode Labels</h2><section className="panel"><select value={qty} onChange={e=>setQty(+e.target.value)}><option value={15}>15 labels</option><option value={30}>30 labels</option><option value={50}>50 labels</option></select>{products.map(p=><label className="check"><input type="checkbox" onChange={e=>setIds(x=>e.target.checked?[...x,p.id]:x.filter(i=>i!==p.id))}/>{p.name} • {p.barcode}</label>)}<button onClick={async()=>{const r=await fetch(`${API}/barcodes/pdf`,{method:"POST",headers:{Authorization:`Bearer ${token()}`,"Content-Type":"application/json"},body:JSON.stringify({product_ids:ids,labels_each:qty})});if(!r.ok){alert("PDF failed");return}const u=URL.createObjectURL(await r.blob());const a=document.createElement("a");a.href=u;a.download="barcode-labels.pdf";a.click();URL.revokeObjectURL(u)}}>Download A4 PDF</button></section></>}
function Audit({rows}:any){return <><h2>Audit Timeline</h2>{rows.map(r=><div className="panel"><b>{r.action}</b><small>{r.created_at} • user {r.user_id} • ref {r.reference}</small><div>{r.old} → {r.new}</div></div>)}</>}
function Settings(){return <><h2>Settings / Backup</h2><section className="panel"><button onClick={()=>window.open(`${API}/backup`)}>Download verified-format backup</button><p>Restore is owner-only and destructive. Validate it on a disposable PostgreSQL database before production restore.</p></section></>}
function Login({onLogin}:any){const [u,setU]=useState("owner"),[p,setP]=useState("owner123"),[e,setE]=useState("");return <div className="login"><div className="panel"><h1>YASH PROVISION STORE</h1><input value={u} onChange={x=>setU(x.target.value)} placeholder="Username"/><input type="password" value={p} onChange={x=>setP(x.target.value)} placeholder="Password"/><button className="primary" onClick={async()=>{try{await api("/auth/bootstrap",{method:"POST"});const d=await api("/auth/login",{method:"POST",body:JSON.stringify({username:u,password:p})});localStorage.setItem(key,d.token);onLogin(d.user)}catch(x:any){setE(x.message)}}}>Login</button><small>{e}</small></div></div>}
function Modal({title,close,children}:any){return <div className="modal"><div className="modalbox"><button className="x" onClick={close}>×</button><h3>{title}</h3>{children}</div></div>}
function Camera({close,onCode}:any){const video=useRef<HTMLVideoElement>(null),reader=useRef<BrowserMultiFormatReader>();const [err,setErr]=useState("");useEffect(()=>{let active=true;reader.current=new BrowserMultiFormatReader();reader.current.decodeFromConstraints({video:{facingMode:{ideal:"environment"}}},video.current!, (r,e)=>{if(active&&r){active=false;onCode(r.getText());reader.current?.reset()}}).catch((e:any)=>setErr(e.message||"Camera unavailable"));return()=>{active=false;reader.current?.reset()}},[]);return <Modal title="Live Barcode Scanner" close={close}><video ref={video} autoPlay muted playsInline className="video"/><p>{err||"Point the back camera at a barcode."}</p><input id="manual" placeholder="Manual barcode"/><button onClick={()=>{const v=(document.getElementById("manual") as HTMLInputElement).value;if(v)onCode(v)}}>Use barcode</button></Modal>}
function Voice({close,setCmd,onAI}:any){const [recording,setRecording]=useState(false),[err,setErr]=useState(""),rec=useRef<MediaRecorder>(),chunks=useRef<Blob[]>([]);const start=async()=>{try{const s=await navigator.mediaDevices.getUserMedia({audio:true});chunks.current=[];rec.current=new MediaRecorder(s);rec.current.ondataavailable=e=>chunks.current.push(e.data);rec.current.onstop=async()=>{s.getTracks().forEach(t=>t.stop());const fd=new FormData();fd.append("file",new Blob(chunks.current,{type:rec.current?.mimeType||"audio/webm"}),"voice.webm");try{const d=await api("/voice/transcribe",{method:"POST",body:fd});setCmd(d.text);setRecording(false)}catch(e:any){setErr(e.message);setRecording(false)}};rec.current.start();setRecording(true)}catch(e:any){setErr(e.message)}};return <Modal title="Hindi / English Voice" close={close}><p>Record → transcribe → edit transcript → preview → confirm.</p>{recording?<button className="primary" onClick={()=>rec.current?.stop()}>Stop recording</button>:<button onClick={start}>Start recording</button>}{err&&<small>{err}</small>}<button onClick={onAI}>Preview command</button></Modal>}
createRoot(document.getElementById("root")!).render(<App/>);
